from typing import List, Optional
from pydantic import BaseModel, Field

class SourceCitation(BaseModel):
    """Schema for retrieved document chunks cited as sources."""
    source_name: str = Field(..., description="Name of the source document/file")
    content: str = Field(..., description="The chunk text context used")
    score: Optional[float] = Field(None, description="Similarity score from vector store")
    page: Optional[int] = Field(None, description="Page number the context was extracted from")

class ChatRequest(BaseModel):
    """Request model for the chat endpoint."""
    question: str = Field(..., min_length=1, description="Question to ask the RAG system")
    history: Optional[List[List[str]]] = Field(
        default=None, 
        description="Optional list of [user_message, assistant_message] pairs representing chat history"
    )
    session_id: Optional[str] = Field(None, description="Chat session ID to log the conversation under")

class ChatResponse(BaseModel):
    """Response model for the chat endpoint."""
    answer: str = Field(..., description="The answer generated by the LLM")
    sources: List[SourceCitation] = Field(default=[], description="List of source document citations")
